"""add_assessment_module

Revision ID: 9980b63bbc4b
Revises: c26bf3539818
Create Date: 2026-03-25 01:47:34.107074+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9980b63bbc4b'
down_revision: Union[str, None] = 'c26bf3539818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('assessment_type', sa.Enum('MMSE', 'MOCA', 'CDR', 'OTHER', name='assessmenttype'), nullable=False),
    sa.Column('evaluation_date', sa.Date(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status_diagnosis', sa.Enum('NORMAL', 'MCI', 'MILD', 'MODERATE', 'SEVERE', name='cognitivestatus'), nullable=False),
    sa.Column('evaluator_name', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant isolation key — enforced by PostgreSQL RLS policy'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_evaluation_date'), 'assessments', ['evaluation_date'], unique=False)
    op.create_index(op.f('ix_assessments_patient_id'), 'assessments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_assessments_tenant_id'), 'assessments', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessments_tenant_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_patient_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_evaluation_date'), table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###
